# Generated by Django 5.1.7 on 2025-04-15 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorship',
            name='mentees',
            field=models.ManyToManyField(blank=True, related_name='menteeships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee')], default='mentee', max_length=10),
        ),
    ]
